version: '3.8'

services:
  # Application principale (Django + Nginx)
  web:
    build:
      context: .
      dockerfile: Dockerfile.railway
    environment:
      - DEBUG=False
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=*.railway.app
    ports:
      - "8000:8000"
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    restart: unless-stopped

  # Service Chatbot (optionnel - peut être intégré dans web)
  chatbot:
    build:
      context: .
      dockerfile: Dockerfile.chatbot
    environment:
      - DEBUG=False
      - DATABASE_URL=${DATABASE_URL}
      - SECRET_KEY=${SECRET_KEY}
      - ALLOWED_HOSTS=*.railway.app
    ports:
      - "8001:8001"
    volumes:
      - ~/.cache/huggingface:/root/.cache/huggingface
    restart: unless-stopped
    depends_on:
      - web

volumes:
  static_volume:
  media_volume:
