services:
  - type: web
    name: parcinfo-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: gunicorn ParcInfo.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: *.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: parcinfo-db
          property: connectionString

  - type: web
    name: parcinfo-chatbot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python manage.py runserver 0.0.0.0:$PORT --settings=ParcInfo.settings
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: *.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: parcinfo-db
          property: connectionString

databases:
  - name: parcinfo-db
    plan: free
