# Generated by Django 5.2.4 on 2025-07-23 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande_informatique', '0003_remove_commande_date_garantie_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterielInformatique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_serie", models.CharField(max_length=100, unique=True)),
                ("code_inventaire", models.CharField(max_length=100, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("affecte", "Affecté"),
                            ("en_panne", "En panne"),
                            ("en_maintenance", "En maintenance"),
                        ],
                        default="nouveau",
                        max_length=20,
                    ),
                ),
                (
                    "public",
                    models.BooleanField(
                        choices=[(True, "Oui"), (False, "Non")], default=True
                    ),
                ),
                (
                    "lieu_stockage",
                    models.CharField(
                        choices=[
                            ("etage1", "Etage 1"),
                            ("etage2", "Etage 2"),
                            ("etage3", "Etage 3"),
                        ],
                        default="etage1",
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("date_service", models.DateField()),
                ("date_fin_garantie", models.DateField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fournisseur", models.CharField(max_length=100)),
                ("numero_facture", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiels",
                        to="commande_informatique.commande",
                    ),
                ),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiels",
                        to="commande_informatique.lignecommande",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
