# Generated by Django 5.2.4 on 2025-07-27 22:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commande_informatique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterielInformatique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_serie", models.CharField(max_length=100)),
                ("code_inventaire", models.CharField(max_length=100)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("affecte", "Affecté"),
                            ("en panne", "En panne"),
                            ("en maintenance", "En maintenance"),
                        ],
                        default="nouveau",
                        max_length=50,
                    ),
                ),
                ("public", models.BooleanField(default=True)),
                (
                    "lieu_stockage",
                    models.CharField(
                        choices=[
                            ("etage1", "Etage 1"),
                            ("etage2", "Etage 2"),
                            ("etage3", "Etage 3"),
                        ],
                        default="etage1",
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiels",
                        to="commande_informatique.commande",
                    ),
                ),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiels",
                        to="commande_informatique.lignecommande",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
