# Generated by Django 5.2.4 on 2025-07-25 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiel_informatique", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="materielinformatique",
            name="date_fin_garantie",
        ),
        migrations.RemoveField(
            model_name="materielinformatique",
            name="date_service",
        ),
        migrations.RemoveField(
            model_name="materielinformatique",
            name="description",
        ),
        migrations.RemoveField(
            model_name="materielinformatique",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="materielinformatique",
            name="fournisseur",
        ),
        migrations.RemoveField(
            model_name="materielinformatique",
            name="numero_facture",
        ),
        migrations.RemoveField(
            model_name="materielinformatique",
            name="prix_unitaire",
        ),
        migrations.AlterField(
            model_name="materielinformatique",
            name="code_inventaire",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="materielinformatique",
            name="numero_serie",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="materielinformatique",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="materielinformatique",
            name="statut",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("affecte", "Affecté"),
                    ("en panne", "En panne"),
                    ("en maintenance", "En maintenance"),
                ],
                default="nouveau",
                max_length=50,
            ),
        ),
    ]
