# Generated by Django 5.2.4 on 2025-07-30 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiel_informatique", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielinformatique",
            name="code_inventaire",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="materielinformatique",
            name="numero_serie",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
