# Generated by Django 5.2.4 on 2025-09-04 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "materiel_informatique",
            "0002_alter_materielinformatique_code_inventaire_and_more",
        ),
    ]

    operations = []
