# Generated by Django 5.2.4 on 2025-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiel_informatique", "0003_auto_20250904_1856"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielinformatique",
            name="statut",
            field=models.CharField(
                choices=[
                    ("nouveau", "Nouveau"),
                    ("affecte", "Affecté"),
                    ("en_panne", "En panne"),
                    ("en_maintenance", "En maintenance"),
                ],
                default="nouveau",
                max_length=50,
            ),
        ),
    ]
