# Generated by Django 5.2.4 on 2025-07-22 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                (
                    "if_fiscal",
                    models.CharField(
                        max_length=50,
                        unique=True,
                        verbose_name="Identifiant Fiscal (IF)",
                    ),
                ),
                (
                    "ice",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Identifiant Commun de l'Entreprise (ICE)",
                    ),
                ),
                (
                    "registre_commerce",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        null=True,
                        verbose_name="Registre du Commerce (RC)",
                    ),
                ),
                (
                    "adresse",
                    models.TextField(blank=True, null=True, verbose_name="Adresse"),
                ),
            ],
        ),
    ]
