# Generated by Django 5.2.4 on 2025-07-26 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commande_bureau", "0002_commandebureau_lignecommandebureau"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MaterielBureau",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_inventaire", models.CharField(max_length=100, unique=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("Opérationnel", "Opérationnel"),
                            ("Réparation", "Réparation"),
                            ("Réforme", "Réforme"),
                        ],
                        default="Opérationnel",
                        max_length=50,
                    ),
                ),
                (
                    "lieu_stockage",
                    models.CharField(
                        choices=[
                            ("etage1", "Etage 1"),
                            ("etage2", "Etage 2"),
                            ("etage3", "Etage 3"),
                        ],
                        default="etage1",
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("date_creation", models.DateTimeField(auto_now_add=True)),
                ("date_modification", models.DateTimeField(auto_now=True)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiels_bureau",
                        to="commande_bureau.commandebureau",
                    ),
                ),
                (
                    "ligne_commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="materiels_bureau",
                        to="commande_bureau.lignecommandebureau",
                    ),
                ),
                (
                    "utilisateur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Matériel de bureau",
                "verbose_name_plural": "Matériels de bureau",
                "ordering": ["-date_creation"],
            },
        ),
    ]
