# Generated by Django 5.2.4 on 2025-08-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiel_bureautique", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielbureau",
            name="statut",
            field=models.CharField(
                choices=[
                    ("Opérationnel", "Opérationnel"),
                    ("affecte", "Affecté"),
                    ("Réparation", "Réparation"),
                    ("Réforme", "Réforme"),
                ],
                default="Opérationnel",
                max_length=50,
            ),
        ),
    ]
