# Generated by Django 5.2.4 on 2025-07-26 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiel_bureautique", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielbureau",
            name="lieu_stockage",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "---------"),
                    ("etage1", "Etage 1"),
                    ("etage2", "Etage 2"),
                    ("etage3", "Etage 3"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
