# Generated by Django 5.2.4 on 2025-09-04 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiel_bureautique", "0002_add_affecte_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielbureau",
            name="statut",
            field=models.CharField(
                choices=[
                    ("operationnel", "Opérationnel"),
                    ("affecte", "Affecté"),
                    ("reparation", "Réparation"),
                    ("reforme", "Réforme"),
                ],
                default="operationnel",
                max_length=50,
            ),
        ),
    ]
