# Generated by Django 5.2.4 on 2025-09-04 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materiel_bureautique", "0003_fix_status_choices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materielbureau",
            name="statut",
            field=models.CharField(
                choices=[
                    ("operationnel", "Opérationnel"),
                    ("affecte", "Affecté"),
                    ("en_reparation", "En réparation"),
                    ("hors_service", "Hors service"),
                ],
                default="operationnel",
                max_length=50,
            ),
        ),
    ]
