apiVersion: v1
kind: Service
metadata:
  name: chatbot-service
  namespace: parcinfo
  labels:
    app: chatbot
spec:
  type: NodePort
  ports:
  - port: 8001
    targetPort: 8001
    nodePort: 30081
  selector:
    app: chatbot
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chatbot
  namespace: parcinfo
  labels:
    app: chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chatbot
  template:
    metadata:
      labels:
        app: chatbot
    spec:
      containers:
      - name: chatbot
        image: parcinfo-chatbot:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8001
          hostPort: 8001
        volumeMounts:
        - name: huggingface-cache
          mountPath: /root/.cache/huggingface
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DEBUG
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: SECRET_KEY
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: ALLOWED_HOSTS
        - name: CSRF_TRUSTED_ORIGINS
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: CSRF_TRUSTED_ORIGINS
        - name: TRANSFORMERS_CACHE
          value: "/root/.cache/huggingface"
        - name: HF_HOME
          value: "/root/.cache/huggingface"
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        # livenessProbe:
        #   httpGet:
        #     path: /health/
        #     port: 8001
        #   initialDelaySeconds: 60
        #   periodSeconds: 30
        # readinessProbe:
        #   httpGet:
        #     path: /health/
        #     port: 8001
        #   initialDelaySeconds: 30
        #   periodSeconds: 10
      volumes:
      - name: huggingface-cache
        emptyDir: {}
