# PostgreSQL déployé dans Kubernetes (désactivé - utilisation de la base locale)
# apiVersion: v1
# kind: Service
# metadata:
#   name: postgres-service
#   namespace: parcinfo
#   labels:
#     app: postgres
# spec:
#   ports:
#   - port: 5432
#     targetPort: 5432
#   selector:
#     app: postgres
# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: postgres
#   namespace: parcinfo
#   labels:
#     app: postgres
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: postgres
#   template:
#     metadata:
#       labels:
#         app: postgres
#     spec:
#       containers:
#       - name: postgres
#         image: pgvector/pgvector:pg15
#         imagePullPolicy: IfNotPresent
#         ports:
#         - containerPort: 5432
#         env:
#         - name: POSTGRES_DB
#           value: "parcinfo"
#         - name: POSTGRES_USER
#           value: "parcinfo"
#         - name: POSTGRES_PASSWORD
#           value: "parcinfo_password"
#         - name: POSTGRES_INITDB_ARGS
#           value: "--auth-host=scram-sha-256"
#         command: ["docker-entrypoint.sh", "postgres", "-c", "shared_preload_libraries=vector"]
#         volumeMounts:
#         - name: postgres-storage
#           mountPath: /var/lib/postgresql/data
#         resources:
#           requests:
#             memory: "256Mi"
#             cpu: "100m"
#           limits:
#             memory: "512Mi"
#             cpu: "250m"
#       volumes:
#       - name: postgres-storage
#         emptyDir: {}
