apiVersion: v1
kind: Service
metadata:
  name: streamlit-service
  namespace: parcinfo
  labels:
    app: streamlit
spec:
  type: NodePort
  ports:
  - port: 8501
    targetPort: 8501
    nodePort: 30085
  selector:
    app: streamlit
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: streamlit
  namespace: parcinfo
  labels:
    app: streamlit
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - name: streamlit
        image: parcinfo-streamlit:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8501
          hostPort: 8501
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DEBUG
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_PORT
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: DB_PASSWORD
        - name: SECRET_KEY
          valueFrom:
            configMapKeyRef:
              name: parcinfo-config
              key: SECRET_KEY
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8501
          initialDelaySeconds: 10
          periodSeconds: 5
