# Generated by Django 5.2.4 on 2025-08-07 16:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatbotInteraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=100)),
                ("user_query", models.TextField()),
                (
                    "detected_intent",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("sql_attempted", models.BooleanField(default=False)),
                ("sql_results", models.IntegerField(default=0)),
                ("rag_results", models.IntegerField(default=0)),
                ("final_response", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-timestamp"],
            },
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_commande", models.CharField(max_length=50, unique=True)),
                ("date_commande", models.DateField()),
                (
                    "mode_passation",
                    models.CharField(
                        choices=[
                            ("appel_offres", "Appel d'offres"),
                            ("devis", "Devis"),
                            ("bon_commande", "Bon de commande"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "montant_total_ht",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("numero_facture", models.CharField(blank=True, max_length=50)),
                ("date_reception", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="DemandeEquipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("categorie", models.CharField(max_length=100)),
                ("type_article", models.CharField(max_length=100)),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("nouvelle", "Nouvelle demande"),
                            ("renouvellement", "Renouvellement"),
                            ("reparation", "Réparation"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("rejetee", "Rejetée"),
                            ("traitee", "Traitée"),
                        ],
                        default="en_attente",
                        max_length=50,
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=255)),
                ("if_fiscal", models.CharField(blank=True, max_length=50)),
                ("ice", models.CharField(blank=True, max_length=50)),
                ("registre_commerce", models.CharField(blank=True, max_length=50)),
                ("adresse", models.TextField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("telephone", models.CharField(blank=True, max_length=50)),
                ("specialite", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_livraison_prevue", models.DateField()),
                ("date_livraison_effective", models.DateField(blank=True, null=True)),
                (
                    "statut_livraison",
                    models.CharField(
                        choices=[
                            ("prevue", "Prévue"),
                            ("en_cours", "En cours"),
                            ("livree", "Livrée"),
                            ("retardee", "Retardée"),
                            ("annulee", "Annulée"),
                        ],
                        default="prevue",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MaterielInformatique",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("numero_serie", models.CharField(blank=True, max_length=255)),
                ("code_inventaire", models.CharField(max_length=50, unique=True)),
                ("designation", models.CharField(max_length=255)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_service", "En service"),
                            ("en_panne", "En panne"),
                            ("en_reparation", "En réparation"),
                            ("hors_service", "Hors service"),
                            ("reserve", "En réserve"),
                        ],
                        default="en_service",
                        max_length=50,
                    ),
                ),
                ("lieu_stockage", models.CharField(blank=True, max_length=255)),
                ("observation", models.TextField(blank=True)),
                ("date_service", models.DateField(blank=True, null=True)),
                ("date_fin_garantie", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="vectorsearchlog",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RenameIndex(
            model_name="vectorsearchlog",
            new_name="chatbot_vec_timesta_09856b_idx",
            old_name="chatbot_vec_timesta_109208_idx",
        ),
        migrations.RenameIndex(
            model_name="vectorsearchlog",
            new_name="chatbot_vec_user_id_5ddf89_idx",
            old_name="chatbot_vec_user_id_2ff864_idx",
        ),
        migrations.AddField(
            model_name="vectorsearchlog",
            name="error_message",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name="vectorsearchlog",
            table=None,
        ),
        migrations.AddIndex(
            model_name="chatbotinteraction",
            index=models.Index(
                fields=["session_id"], name="chatbot_cha_session_668d9f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatbotinteraction",
            index=models.Index(
                fields=["timestamp"], name="chatbot_cha_timesta_ac3628_idx"
            ),
        ),
        migrations.AddField(
            model_name="demandeequipement",
            name="demandeur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="fournisseur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot.fournisseur"
            ),
        ),
        migrations.AddField(
            model_name="livraison",
            name="commande",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chatbot.commande"
            ),
        ),
    ]
