# Generated by Django 5.2.4 on 2025-08-08 22:58

import pgvector.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0002_chatbotinteraction_commande_demandeequipement_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="documentvector",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"], lists=100, name="document_vector_embedding_idx"
            ),
        ),
    ]
