# Generated by Django 5.2.4 on 2025-08-09 13:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0003_documentvector_document_vector_embedding_idx"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IntentExample",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("intent", models.CharField(max_length=50)),
                ("phrase", models.TextField()),
                ("weight", models.FloatField(default=1.0)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("user", "user"),
                            ("system", "system"),
                            ("import", "import"),
                        ],
                        default="user",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["intent"], name="chatbot_int_intent_66fc7a_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="chatbot_int_created_c716d8_idx"
                    ),
                ],
                "unique_together": {("intent", "phrase")},
            },
        ),
        migrations.CreateModel(
            name="ChatbotFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100)),
                ("query", models.TextField()),
                ("intent_pred", models.CharField(blank=True, max_length=50, null=True)),
                ("entities_pred", models.JSONField(blank=True, null=True)),
                (
                    "intent_final",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("entities_final", models.JSONField(blank=True, null=True)),
                (
                    "rating",
                    models.SmallIntegerField(blank=True, help_text="1-5", null=True),
                ),
                (
                    "reward",
                    models.FloatField(
                        default=0.0, help_text="Reinforcement signal [-1,1]"
                    ),
                ),
                ("response_snippet", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id"], name="chatbot_cha_session_3dc15b_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="chatbot_cha_created_933458_idx"
                    ),
                    models.Index(
                        fields=["user"], name="chatbot_cha_user_id_a8a6e7_idx"
                    ),
                ],
            },
        ),
    ]
