# Generated by Django 5.2.4 on 2025-08-09 21:19

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0004_intentexample_chatbotfeedback"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="fournisseur",
        ),
        migrations.RemoveField(
            model_name="livraison",
            name="commande",
        ),
        migrations.RemoveField(
            model_name="demandeequipement",
            name="demandeur",
        ),
        migrations.DeleteModel(
            name="MaterielInformatique",
        ),
        migrations.RemoveField(
            model_name="vectorsearchlog",
            name="user",
        ),
        migrations.AlterModelOptions(
            name="chatbotfeedback",
            options={},
        ),
        migrations.AlterModelOptions(
            name="chatmessage",
            options={"ordering": ["-timestamp"]},
        ),
        migrations.RemoveIndex(
            model_name="chatbotfeedback",
            name="chatbot_cha_created_933458_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentvector",
            name="chatbot_doc_model_n_8588a7_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentvector",
            name="chatbot_doc_is_acti_3876b2_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentvector",
            name="chatbot_doc_indexed_d7dda2_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentvector",
            name="document_vector_embedding_idx",
        ),
        migrations.RemoveIndex(
            model_name="intentexample",
            name="chatbot_int_created_c716d8_idx",
        ),
        migrations.AlterUniqueTogether(
            name="documentvector",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="entities_final",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="entities_pred",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="intent_final",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="intent_pred",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="response_snippet",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="reward",
        ),
        migrations.RemoveField(
            model_name="chatbotinteraction",
            name="rag_results",
        ),
        migrations.RemoveField(
            model_name="chatbotinteraction",
            name="sql_attempted",
        ),
        migrations.RemoveField(
            model_name="chatbotinteraction",
            name="sql_results",
        ),
        migrations.RemoveField(
            model_name="intentexample",
            name="source",
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="feedback_text",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="intent_corrected",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="intent_predicted",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="chatbotfeedback",
            name="rating",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="chatbotfeedback",
            name="session_id",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="chatbotfeedback",
            name="user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="documentvector",
            name="content",
            field=models.TextField(),
        ),
        migrations.AddIndex(
            model_name="chatbotfeedback",
            index=models.Index(
                fields=["intent_predicted"], name="chatbot_cha_intent__d9700e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["session_id"], name="chatbot_cha_session_e625f8_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chatmessage",
            index=models.Index(
                fields=["timestamp"], name="chatbot_cha_timesta_d01b0b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentvector",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"],
                lists=100,
                name="document_vector_ivfflat_idx",
                opclasses=["vector_l2_ops"],
            ),
        ),
        migrations.AddIndex(
            model_name="documentvector",
            index=models.Index(
                fields=["model_name"], name="chatbot_doc_model_n_934ae9_idx"
            ),
        ),
        migrations.DeleteModel(
            name="Fournisseur",
        ),
        migrations.DeleteModel(
            name="Commande",
        ),
        migrations.DeleteModel(
            name="Livraison",
        ),
        migrations.DeleteModel(
            name="DemandeEquipement",
        ),
        migrations.DeleteModel(
            name="VectorSearchLog",
        ),
        migrations.RemoveField(
            model_name="documentvector",
            name="priority",
        ),
        migrations.RemoveField(
            model_name="documentvector",
            name="source",
        ),
    ]
