# Generated by Django 5.2.4 on 2025-08-09 21:34

import django.db.models.deletion
import pgvector.django
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chatbot", "0005_remove_commande_fournisseur_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="chatbotfeedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveIndex(
            model_name="chatbotfeedback",
            name="chatbot_cha_user_id_a8a6e7_idx",
        ),
        migrations.RemoveIndex(
            model_name="chatbotfeedback",
            name="chatbot_cha_intent__d9700e_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentvector",
            name="document_vector_ivfflat_idx",
        ),
        migrations.RemoveIndex(
            model_name="documentvector",
            name="chatbot_doc_model_n_934ae9_idx",
        ),
        migrations.RemoveIndex(
            model_name="intentexample",
            name="chatbot_int_intent_66fc7a_idx",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="feedback_text",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="intent_corrected",
        ),
        migrations.RemoveField(
            model_name="chatbotfeedback",
            name="intent_predicted",
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="entities_final",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="entities_pred",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="intent_final",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="intent_pred",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="response_snippet",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chatbotfeedback",
            name="reward",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="chatbotinteraction",
            name="rag_results",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="chatbotinteraction",
            name="sql_attempted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="chatbotinteraction",
            name="sql_results",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="documentvector",
            name="priority",
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name="documentvector",
            name="source",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="intentexample",
            name="source",
            field=models.CharField(
                choices=[("user", "User"), ("system", "System"), ("import", "Import")],
                default="system",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="chatbotfeedback",
            name="rating",
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="chatbotfeedback",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="documentvector",
            unique_together={("content_type", "object_id")},
        ),
        migrations.AddIndex(
            model_name="chatbotfeedback",
            index=models.Index(
                fields=["created_at"], name="chatbot_cha_created_933458_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="documentvector",
            index=pgvector.django.IvfflatIndex(
                fields=["embedding"], lists=100, name="embedding_idx"
            ),
        ),
    ]
