# Generated by Django 5.2.4 on 2025-07-27 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("fournisseurs", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Commande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mode_passation",
                    models.CharField(
                        choices=[
                            ("BC", "Bon de Commande"),
                            ("Contrat", "Contrat"),
                            ("AO", "Appel d'Offres"),
                        ],
                        max_length=10,
                    ),
                ),
                ("numero_commande", models.CharField(max_length=100)),
                ("date_commande", models.DateField()),
                ("date_reception", models.DateField(blank=True, null=True)),
                (
                    "numero_facture",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "duree_garantie_valeur",
                    models.PositiveIntegerField(
                        default=1, verbose_name="Durée de garantie"
                    ),
                ),
                (
                    "duree_garantie_unite",
                    models.CharField(
                        choices=[
                            ("jour", "Jour(s)"),
                            ("mois", "Mois"),
                            ("annee", "Année"),
                        ],
                        default="mois",
                        max_length=10,
                        verbose_name="Unité de durée",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="fournisseurs.fournisseur",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Description",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="commande_informatique.designation",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="commande_informatique.commande",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commande_informatique.description",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commande_informatique.designation",
                    ),
                ),
            ],
        ),
    ]
