# Generated by Django 5.2.4 on 2025-07-23 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_informatique", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="description",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="designation",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="prix_unitaire",
        ),
        migrations.RemoveField(
            model_name="commande",
            name="quantite",
        ),
        migrations.CreateModel(
            name="LigneCommande",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                ("prix_unitaire", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "commande",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lignes",
                        to="commande_informatique.commande",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commande_informatique.description",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="commande_informatique.designation",
                    ),
                ),
            ],
        ),
    ]
