# Generated by Django 5.2.4 on 2025-08-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande_informatique', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='public',
            field=models.BooleanField(default=True),
        ),
    ]
