# Generated by Django 5.2.5 on 2025-09-05 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_informatique", "0002_description_public"),
    ]

    operations = [
        migrations.AddField(
            model_name="designation",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
