# Generated by Django 5.2.4 on 2025-07-23 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_informatique", "0002_remove_commande_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="commande",
            name="date_garantie",
        ),
        migrations.AddField(
            model_name="commande",
            name="duree_garantie_unite",
            field=models.CharField(
                choices=[("jour", "Jour(s)"), ("mois", "Mois"), ("annee", "Année")],
                default="mois",
                max_length=10,
                verbose_name="Unité de durée",
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="duree_garantie_valeur",
            field=models.PositiveIntegerField(
                default=1, verbose_name="Durée de garantie"
            ),
        ),
    ]
