# Generated by Django 5.2.5 on 2025-09-05 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_informatique", "0003_designation_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designation",
            name="public",
        ),
        migrations.AddField(
            model_name="designation",
            name="ispublic",
            field=models.BooleanField(default=True, verbose_name="Public"),
        ),
    ]
