# Generated by Django 5.2.5 on 2025-09-05 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commande_informatique",
            "0004_remove_designation_public_designation_ispublic",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designation",
            name="ispublic",
        ),
        migrations.AddField(
            model_name="designation",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
