# Generated by Django 5.2.4 on 2025-07-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Equipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sn_article",
                    models.CharField(max_length=50, verbose_name="SN_ARTICLE"),
                ),
                (
                    "code_inventaire",
                    models.CharField(max_length=50, verbose_name="Code N° Inventaire"),
                ),
                (
                    "date_service",
                    models.DateField(
                        blank=True, null=True, verbose_name="Date de service"
                    ),
                ),
                ("designation", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                (
                    "prix_ht_mad",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("fournisseur", models.CharField(blank=True, max_length=100)),
                ("numero_facture", models.CharField(blank=True, max_length=50)),
                ("operation", models.CharField(blank=True, max_length=50)),
                ("reparation", models.BooleanField(default=False)),
                ("is_public", models.BooleanField(default=False)),
                ("lieu_affectation", models.CharField(blank=True, max_length=100)),
                ("observations", models.TextField(blank=True)),
            ],
        ),
    ]
