# Generated by Django 5.2.4 on 2025-07-18 19:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="equipement",
            name="date_service",
        ),
        migrations.RemoveField(
            model_name="equipement",
            name="operation",
        ),
        migrations.RemoveField(
            model_name="equipement",
            name="reparation",
        ),
        migrations.RemoveField(
            model_name="equipement",
            name="sn_article",
        ),
        migrations.AddField(
            model_name="equipement",
            name="date_garantie",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de garantie"
            ),
        ),
        migrations.AddField(
            model_name="equipement",
            name="statut",
            field=models.CharField(
                choices=[
                    ("affecte", "Affecté"),
                    ("panne", "En panne"),
                    ("maintenance", "Maintenance"),
                ],
                default="affecte",
                max_length=20,
                verbose_name="Statut",
            ),
        ),
        migrations.AddField(
            model_name="equipement",
            name="utilisateur",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Utilisateur",
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="description",
            field=models.TextField(blank=True, verbose_name="Description"),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="designation",
            field=models.CharField(max_length=100, verbose_name="Désignation"),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="fournisseur",
            field=models.CharField(
                blank=True, max_length=100, verbose_name="Fournisseur"
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="is_public",
            field=models.BooleanField(default=False, verbose_name="Public"),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="lieu_affectation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("etage1", "Étage 1"),
                    ("etage2", "Étage 2"),
                    ("etage3", "Étage 3"),
                ],
                max_length=20,
                verbose_name="Lieu d'affectation",
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="numero_facture",
            field=models.CharField(
                blank=True, max_length=50, verbose_name="N° Facture"
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="observations",
            field=models.TextField(blank=True, verbose_name="Observations"),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="prix_ht_mad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix HT (MAD)",
            ),
        ),
    ]
