# Generated by Django 5.2.4 on 2025-07-18 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0002_remove_equipement_date_service_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipement",
            name="date_service",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de service"
            ),
        ),
        migrations.AddField(
            model_name="equipement",
            name="sn_article",
            field=models.CharField(
                default=1, max_length=50, verbose_name="N° de série"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="equipement",
            name="date_garantie",
            field=models.DateField(blank=True, null=True, verbose_name="Garantie"),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="lieu_affectation",
            field=models.CharField(
                blank=True,
                choices=[
                    ("etage1", "Étage 1"),
                    ("etage2", "Étage 2"),
                    ("etage3", "Étage 3"),
                ],
                max_length=20,
                verbose_name="Lieu",
            ),
        ),
        migrations.AlterField(
            model_name="equipement",
            name="prix_ht_mad",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                verbose_name="Prix HT en MAD",
            ),
        ),
    ]
