# Generated by Django 5.2.4 on 2025-07-18 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0003_equipement_date_service_equipement_sn_article_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="equipement",
            name="date_garantie",
            field=models.DateField(
                blank=True, null=True, verbose_name="Date de garantie"
            ),
        ),
    ]
