# Generated by Django 5.2.4 on 2025-07-18 22:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0004_alter_equipement_date_garantie"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Materiel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code_inventaire", models.CharField(max_length=100, unique=True)),
                ("date_mise_en_service", models.DateField(blank=True, null=True)),
                (
                    "description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("designation", models.TextField(blank=True, null=True)),
                ("prix_ht_mad", models.FloatField(blank=True, null=True)),
                (
                    "fournisseur",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "etat_article",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("opérationnel", "Opérationnel"),
                            ("réparation", "Réparation"),
                            ("réforme", "Réforme"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "lieu_affectation",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "affecte_a",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="materiels_affectes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Affecté à",
                    ),
                ),
            ],
        ),
    ]
