# Generated by Django 5.2.4 on 2025-07-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipements", "0006_remove_materiel_date_mise_en_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="materiel",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="materiel",
            name="designation",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
