# Generated by Django 5.2.4 on 2025-08-01 09:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commande_bureau", "0001_initial"),
        ("commande_informatique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Livraison",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "numero_commande",
                    models.CharField(max_length=50, verbose_name="Numéro de commande"),
                ),
                (
                    "type_commande",
                    models.CharField(
                        choices=[
                            ("informatique", "Commande Informatique"),
                            ("bureau", "Commande Bureau"),
                        ],
                        max_length=20,
                        verbose_name="Type de commande",
                    ),
                ),
                (
                    "date_livraison_prevue",
                    models.DateField(verbose_name="Date de livraison prévue"),
                ),
                (
                    "date_livraison_effective",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de livraison effective",
                    ),
                ),
                (
                    "statut_livraison",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("en_cours", "En cours"),
                            ("livree", "Livrée"),
                            ("retardee", "Retardée"),
                            ("annulee", "Annulée"),
                        ],
                        default="en_attente",
                        max_length=20,
                        verbose_name="Statut de livraison",
                    ),
                ),
                (
                    "conforme",
                    models.BooleanField(default=True, verbose_name="Conforme"),
                ),
                (
                    "pv_reception_recu",
                    models.BooleanField(
                        default=False,
                        help_text="Cochez si le PV de réception a bien été validé et signé",
                        verbose_name="PV réception validé ?",
                    ),
                ),
                ("notes", models.TextField(blank=True, verbose_name="Notes")),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                (
                    "commande_bureau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commande_bureau.commandebureau",
                        verbose_name="Commande Bureau",
                    ),
                ),
                (
                    "commande_informatique",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="commande_informatique.commande",
                        verbose_name="Commande Informatique",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livraisons_crees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Créé par",
                    ),
                ),
                (
                    "livreur",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livraisons_effectuees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Livreur",
                    ),
                ),
                (
                    "modifie_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="livraisons_modifiees",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Modifié par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Livraison",
                "verbose_name_plural": "Livraisons",
                "ordering": ["-date_creation"],
                "unique_together": {("numero_commande", "type_commande")},
            },
        ),
    ]
