# Generated by Django 5.2.4 on 2025-08-01 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livraison", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="livraison",
            name="livreur",
        ),
    ]
