# Generated by Django 5.2.4 on 2025-08-01 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livraison", "0002_remove_livraison_livreur"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="livraison",
            unique_together=set(),
        ),
    ]
