# Generated by Django 5.2.4 on 2025-08-01 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("livraison", "0003_remove_unique_constraint"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="livraison",
            unique_together={("numero_commande", "type_commande")},
        ),
    ]
