# Generated by Django 5.2.4 on 2025-07-27 22:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                error_messages={"unique": "Un utilisateur avec ce nom existe déjà."},
                help_text="Requis. 150 caractères max. Lettres, chiffres, @/./+/-/_ et espaces autorisés.",
                max_length=150,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Ce champ peut contenir des lettres, chiffres, @/./+/-/_ et espaces.",
                        regex="^[\\w.@+\\- ]+$",
                    )
                ],
            ),
        ),
    ]
