# Generated by Django 5.2.4 on 2025-08-24 11:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationDemande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notification', models.CharField(choices=[('demande_equipement', "Demande d'équipement"), ('demande_bureau', 'Demande bureautique')], max_length=50)),
                ('titre', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('statut_demande', models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('en_cours', 'En cours de traitement'), ('terminee', 'Terminée')], max_length=20)),
                ('demande_id', models.IntegerField(help_text='ID de la demande concernée')),
                ('lu', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_lecture', models.DateTimeField(blank=True, null=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications_demande', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification de demande',
                'verbose_name_plural': 'Notifications de demandes',
                'ordering': ['-date_creation'],
            },
        ),
    ]
