# Generated by Django 5.2.4 on 2025-08-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_notificationdemande'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdemande',
            name='statut_demande',
            field=models.CharField(choices=[('en_attente', 'En attente'), ('approuvee', 'Approuvée'), ('rejetee', 'Rejetée'), ('en_cours', 'En cours de traitement'), ('terminee', 'Terminée'), ('en_attente_signature', 'En attente de signature'), ('signature_requise', 'Signature requise')], max_length=20),
        ),
    ]
