# Generated by Django 5.2.5 on 2025-09-05 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_bureau", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="descriptionbureau",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
