# Generated by Django 5.2.5 on 2025-09-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_bureau", "0002_descriptionbureau_public"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="descriptionbureau",
            name="public",
        ),
        migrations.AddField(
            model_name="designationbureau",
            name="ispublic",
            field=models.BooleanField(default=True, verbose_name="Public"),
        ),
    ]
