# Generated by Django 5.2.5 on 2025-09-05 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_bureau", "0003_remove_descriptionbureau_public_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="designationbureau",
            name="ispublic",
        ),
        migrations.AddField(
            model_name="descriptionbureau",
            name="public",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="designationbureau",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
