# Generated by Django 5.2.5 on 2025-09-05 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commande_bureau", "0004_remove_designationbureau_ispublic_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="descriptionbureau",
            name="public",
        ),
        migrations.RemoveField(
            model_name="designationbureau",
            name="public",
        ),
    ]
