# Generated by Django 5.2.5 on 2025-09-05 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commande_bureau", "0005_add_public_field_to_description_bureau"),
    ]

    operations = [
        migrations.AddField(
            model_name="descriptionbureau",
            name="public",
            field=models.BooleanField(default=True),
        ),
    ]
