# Generated by Django 5.2.4 on 2025-07-19 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(max_length=255, verbose_name="Nom du fournisseur"),
                ),
                (
                    "contact",
                    models.CharField(max_length=100, verbose_name="Contact principal"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "contrat",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Numéro du contrat",
                    ),
                ),
                (
                    "date_derniere_commande",
                    models.DateField(
                        blank=True,
                        null=True,
                        verbose_name="Date de la dernière commande",
                    ),
                ),
            ],
        ),
    ]
