# Generated by Django 5.2.4 on 2025-07-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fournisseur", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="fournisseur",
            options={
                "ordering": ["categorie", "nom"],
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
            },
        ),
        migrations.RemoveField(
            model_name="fournisseur",
            name="contact",
        ),
        migrations.RemoveField(
            model_name="fournisseur",
            name="contrat",
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="categorie",
            field=models.CharField(
                choices=[
                    ("informatique", "Matériel Informatique"),
                    ("bureautique", "Matériel Bureautique"),
                ],
                default="informatique",
                max_length=20,
                verbose_name="Catégorie de matériel",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="fournisseur",
            name="numero_contrat",
            field=models.CharField(
                default="0000", max_length=100, verbose_name="Numéro de contrat"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="email",
            field=models.EmailField(
                default="inconnu", max_length=254, verbose_name="Adresse e-mail"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="fournisseur",
            name="nom",
            field=models.CharField(max_length=100, verbose_name="Nom du fournisseur"),
        ),
    ]
