# Generated by Django 5.2.4 on 2025-07-29 18:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commande_bureau", "0001_initial"),
        ("commande_informatique", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeEquipement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_demande", models.DateTimeField(auto_now_add=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("en_attente", "En attente"),
                            ("approuvee", "Approuvée"),
                            ("refusee", "Refusée"),
                        ],
                        default="en_attente",
                        max_length=20,
                    ),
                ),
                (
                    "categorie",
                    models.CharField(
                        choices=[
                            ("informatique", "Informatique"),
                            ("bureau", "Bureau"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type_article",
                    models.CharField(
                        choices=[
                            ("materiel", "Matériel"),
                            ("fourniture", "Fourniture"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "type_demande",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("renouvellement", "Renouvellement"),
                            ("reparation", "Réparation"),
                            ("service", "Service"),
                            ("deplacement", "Déplacement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("date_approbation", models.DateTimeField(blank=True, null=True)),
                (
                    "demandeur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="demandes_equipement",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "description_bureau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_bureau",
                        to="commande_bureau.descriptionbureau",
                    ),
                ),
                (
                    "description_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_info",
                        to="commande_informatique.description",
                    ),
                ),
                (
                    "designation_bureau",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_bureau",
                        to="commande_bureau.designationbureau",
                    ),
                ),
                (
                    "designation_info",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_info",
                        to="commande_informatique.designation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande d'équipement",
                "verbose_name_plural": "Demandes d'équipement",
                "ordering": ["-date_demande"],
            },
        ),
    ]
