# Generated by Django 5.2.4 on 2025-07-29 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande_equipement", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeequipement",
            name="date_affectation",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
