# Generated by Django 5.2.4 on 2025-07-30 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande_equipement", "0002_demandeequipement_date_affectation"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeequipement",
            name="materiel_selectionne_id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
