# Generated by Django 5.2.4 on 2025-07-31 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande_equipement", "0003_demandeequipement_materiel_selectionne_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeequipement",
            name="date_signature",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="demandeequipement",
            name="decharge_signee",
            field=models.BooleanField(default=False),
        ),
    ]
