# Generated by Django 5.2.4 on 2025-07-31 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande_equipement", "0004_demandeequipement_date_signature_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="demandeequipement",
            name="signature_image",
            field=models.CharField(
                blank=True,
                help_text="Chemin vers l'image de signature électronique",
                max_length=255,
                null=True,
            ),
        ),
    ]
