# Generated by Django 5.2.4 on 2025-07-31 17:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demande_equipement", "0005_demandeequipement_signature_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ArchiveDecharge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "fichier_pdf",
                    models.FileField(
                        upload_to="archives/decharges/",
                        verbose_name="Fichier PDF archivé",
                    ),
                ),
                (
                    "date_archivage",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date d'archivage"
                    ),
                ),
                (
                    "numero_archive",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Numéro d'archive"
                    ),
                ),
                (
                    "statut_archive",
                    models.CharField(
                        choices=[
                            ("actif", "Actif"),
                            ("inactif", "Inactif"),
                            ("supprime", "Supprimé"),
                        ],
                        default="actif",
                        max_length=20,
                        verbose_name="Statut de l'archive",
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes d'archivage"),
                ),
                (
                    "archive_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Archivé par",
                    ),
                ),
                (
                    "demande",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="archive_decharge",
                        to="demande_equipement.demandeequipement",
                    ),
                ),
            ],
            options={
                "verbose_name": "Archive de décharge",
                "verbose_name_plural": "Archives de décharges",
                "ordering": ["-date_archivage"],
            },
        ),
    ]
