# Generated by Django 4.2.7 on 2025-08-16 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("demande_equipement", "0006_archivedecharge"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fourniture",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        max_length=200, verbose_name="Nom de la fourniture"
                    ),
                ),
                (
                    "numero_serie",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Numéro de série"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("informatique", "Informatique"),
                            ("bureautique", "Bureautique"),
                        ],
                        max_length=20,
                        verbose_name="Type de fourniture",
                    ),
                ),
                (
                    "date_creation",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "date_modification",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de modification"
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Fourniture",
                "verbose_name_plural": "Fournitures",
                "ordering": ["nom"],
            },
        ),
        migrations.AddField(
            model_name="demandeequipement",
            name="fourniture",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="demandes_fourniture",
                to="demande_equipement.fourniture",
                verbose_name="Fourniture demandée",
            ),
        ),
    ]
