name: Chatbot ParcInfo Tests

on:
  push:
    paths:
      - 'apps/chatbot/**'
      - 'test_rag_chatbot.py'
      - 'scripts/test_chatbot_*.py'
      - '.github/workflows/chatbot-tests.yml'
  pull_request:
    paths:
      - 'apps/chatbot/**'
      - 'test_rag_chatbot.py'
      - 'scripts/test_chatbot_*.py'
      - '.github/workflows/chatbot-tests.yml'

jobs:
  test-chatbot:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: parcinfo_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y postgresql-client

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_unified.txt

    - name: Set up Django environment
      run: |
        export DJANGO_SETTINGS_MODULE=ParcInfo.settings
        export DATABASE_URL=postgres://postgres:postgres@localhost:5432/parcinfo_test
        python manage.py check

    - name: Run database migrations
      run: |
        export DJANGO_SETTINGS_MODULE=ParcInfo.settings
        export DATABASE_URL=postgres://postgres:postgres@localhost:5432/parcinfo_test
        python manage.py migrate

    - name: Run chatbot tests
      run: |
        export DJANGO_SETTINGS_MODULE=ParcInfo.settings
        export DATABASE_URL=postgres://postgres:postgres@localhost:5432/parcinfo_test
        python test_rag_chatbot.py
      env:
        DJANGO_SETTINGS_MODULE: ParcInfo.settings
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/parcinfo_test

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: chatbot-test-results
        path: |
          test_report_*.json
          *.log
