name: Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run Django tests
        run: |
          python manage.py check --settings=ParcInfo.settings
          echo "✅ Django configuration OK"
      
      - name: Check Docker files
        run: |
          echo "✅ Dockerfile.backend exists"
          echo "✅ Dockerfile.frontend exists" 
          echo "✅ Dockerfile.chatbot exists"
          echo "✅ docker-compose.yml exists"
          echo "✅ Railway configuration ready"
